-- MySQL Script generated by MySQL Workbench
-- Mon Aug 16 00:40:12 2021
-- Model: gbadata    Version: 0.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gbadata
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gbadata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gbadata` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gbadata` ;

-- -----------------------------------------------------
-- Table `gbadata`.`AcademicTeaching`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`AcademicTeaching` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`AcademicTeaching` (
  `idAcademicTeaching` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idAcademicTeaching`),
  INDEX `fk_Academicteaching_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Accessibility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Accessibility` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Accessibility` (
  `idAccessibility` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idAccessibility`),
  INDEX `fk_Accessibility_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`AccessibilityDepartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`AccessibilityDepartment` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`AccessibilityDepartment` (
  `idAccessibilityDepartment` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idAccessibilityDepartment`),
  INDEX `fk_AccessibilityDepartment_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`AddOnInfoHospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`AddOnInfoHospital` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`AddOnInfoHospital` (
  `idAddOnInfoHospital` INT NOT NULL AUTO_INCREMENT,
  `academicTeachingHospital` INT NULL,
  `universityClinic` INT NULL,
  `universityName` VARCHAR(1024) NULL DEFAULT NULL,
  `psychiatricHospital` INT NULL,
  `psychiatricDutyToSupply` INT NULL,
  `extQMbyState` INT NULL,
  `messageNonPerformanceNursingCareGiven` INT NULL,
  `clearingDialogueSQM` INT NULL,
  `clearingDialogueSQMCompleted` INT NULL,
  `medicinesCommission` INT NULL,
  `otherMedicinesWorkingGroup` INT NULL,
  `medicinesWGName` VARCHAR(1024) NULL DEFAULT NULL,
  `medicinesWGInvolvedDepartments` VARCHAR(2048) NULL DEFAULT NULL,
  `noMedicinesWorkingGroup` INT NULL,
  `noPharmacoSafetyPersonInCharge` INT NULL,
  `interinstitutionalErrorReportingConferenceFrequency` VARCHAR(255) NULL DEFAULT NULL,
  `tariffWeeklyWorkingHoursDoctors` VARCHAR(255) NULL DEFAULT NULL,
  `tariffWeeklyWorkingHoursNurses` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idAddOnInfoHospital`),
  INDEX `fk_AddOnInfoHospital_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`AdditionalExternalQualityManagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`AdditionalExternalQualityManagement` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`AdditionalExternalQualityManagement` (
  `idAdditionalExternalQualityManagement` INT NOT NULL AUTO_INCREMENT,
  `section` VARCHAR(1024) NULL DEFAULT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `result` VARCHAR(1024) NULL DEFAULT NULL,
  `measurementPeriod` VARCHAR(1024) NULL DEFAULT NULL,
  `dataGathering` VARCHAR(1024) NULL DEFAULT NULL,
  `calculationRules` VARCHAR(1024) NULL DEFAULT NULL,
  `referenceRange` VARCHAR(1024) NULL DEFAULT NULL,
  `documentationReference` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idAdditionalExternalQualityManagement`),
  INDEX `fk_AdditionalExternalQualityManagement_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Address` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `use` VARCHAR(1024) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `housenumber` VARCHAR(255) NULL DEFAULT NULL,
  `zip` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `URL` VARCHAR(1024) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `text` VARCHAR(1024) NULL DEFAULT NULL,
  `lat` VARCHAR(255) NULL DEFAULT NULL,
  `lon` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`AttendingDoctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`AttendingDoctors` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`AttendingDoctors` (
  `idAttendingDoctors` INT NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(255) NULL,
  `casesPerQuantity` VARCHAR(255) NULL,
  `comment` VARCHAR(1024) NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idAttendingDoctors`),
  INDEX `fk_AttendingDoctors_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`AttendingDoctorsHospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`AttendingDoctorsHospital` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`AttendingDoctorsHospital` (
  `idAttendingDoctorsHospital` INT NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(255) NULL,
  `casesPerQuantity` VARCHAR(255) NULL,
  `comment` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idAttendingDoctorsHospital`),
  INDEX `fk_AttendingDoctors_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`ComplaintManagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`ComplaintManagement` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`ComplaintManagement` (
  `idComplaintManagement` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `URL` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idComplaintManagement`),
  INDEX `fk_ComplaintManagement_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`ContinuingEducation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`ContinuingEducation` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`ContinuingEducation` (
  `idContinuingEducation` INT NOT NULL AUTO_INCREMENT,
  `pplWithDutyForCE` VARCHAR(255) NULL DEFAULT NULL,
  `pplWithBurdenOfProof` VARCHAR(255) NULL DEFAULT NULL,
  `pplWithVerifiedTraining` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idContinuingEducation`),
  INDEX `fk_ContinuingEducation_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Dataset_metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Dataset_metadata` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Dataset_metadata` (
  `idDataset_metadata` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NULL,
  `date` DATE NULL,
  `language` VARCHAR(255) NULL DEFAULT NULL,
  `softwareCompany` VARCHAR(255) NULL DEFAULT NULL,
  `softwareProgram` VARCHAR(255) NULL DEFAULT NULL,
  `softwareVersion` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idDataset_metadata`),
  INDEX `fk_Dataset_metadata_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`DepartmentKeys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`DepartmentKeys` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`DepartmentKeys` (
  `idDepartmentKeys` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idDepartmentKeys`),
  INDEX `fk_DepartmentKeys_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`DepartmentTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`DepartmentTypes` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`DepartmentTypes` (
  `idDepartmentTypes` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `specialized` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idDepartmentTypes`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Departments` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Departments` (
  `idDepartments` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1024) NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `quantityCasesFull` VARCHAR(255) NULL DEFAULT NULL,
  `quantityCasesPartial` VARCHAR(255) NULL DEFAULT NULL,
  `quantityCasesComment` VARCHAR(1024) NULL DEFAULT NULL,
  `accidentInsuranceOutpatientConsultancy` INT NULL DEFAULT NULL,
  `accidentInsuranceInpatientLicence` INT NULL DEFAULT NULL,
  `inpatientOperationsPerformed` INT NULL DEFAULT NULL,
  `targetAgreements` VARCHAR(255) NULL DEFAULT NULL,
  `targetAgreementsComment` VARCHAR(1024) NULL DEFAULT NULL,
  `targetAgreementsNoDKGComment` VARCHAR(1024) NULL DEFAULT NULL,
  `tariffWeeklyWorkingHoursDoctors` VARCHAR(255) NULL DEFAULT NULL,
  `tariffWeeklyWorkingHoursNurses` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idDepartments`))
ENGINE = MyISAM
COMMENT = '	';


-- -----------------------------------------------------
-- Table `gbadata`.`Diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Diagnoses` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Diagnoses` (
  `idDiagnoses` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `cases` VARCHAR(255) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idDiagnoses`),
  INDEX `fk_Diagnoses_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`DiseaseManagementPrograms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`DiseaseManagementPrograms` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`DiseaseManagementPrograms` (
  `idDiseaseManagementPrograms` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1024) NOT NULL,
  `comment` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idDiseaseManagementPrograms`),
  INDEX `fk_DiseaseManagementPrograms_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`EmergencyCareLevelPrerequisitesAssurances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`EmergencyCareLevelPrerequisitesAssurances` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`EmergencyCareLevelPrerequisitesAssurances` (
  `idEmergencyCareLevelPrerequisitesAssurances` INT NOT NULL AUTO_INCREMENT,
  `emergencyCareLevel` VARCHAR(255) NULL DEFAULT NULL,
  `emergencyCareLevelPrerequisitesGiven` VARCHAR(255) NULL DEFAULT NULL,
  `emergencyCareLevelAssuranceGiven` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idEmergencyCareLevelPrerequisitesAssurances`),
  INDEX `fk_EmergencyCareLevelPrerequisitesAssurances_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`ExternalComSystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`ExternalComSystem` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`ExternalComSystem` (
  `idExternalComSystem` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `frequency` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idExternalComSystem`),
  INDEX `fk_InternalComSystem_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`ExternalQMbyState`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`ExternalQMbyState` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`ExternalQMbyState` (
  `idExternalQMbyState` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `participation` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idExternalQMbyState`),
  INDEX `fk_ExternalQMbyState_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`FulfillmentLevelPpUG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`FulfillmentLevelPpUG` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`FulfillmentLevelPpUG` (
  `idFulfillmentLevelPpUG` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(255) NULL DEFAULT NULL,
  `hospitalWard` VARCHAR(255) NULL DEFAULT NULL,
  `shift` VARCHAR(255) NULL DEFAULT NULL,
  `exceptionalCases` VARCHAR(255) NULL DEFAULT NULL,
  `frameOfReference` VARCHAR(255) NULL DEFAULT NULL,
  `degreeOfFulfillment` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idFulfillmentLevelPpUG`),
  INDEX `fk_FulfillmentLevelPpUG_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`FurtherLinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`FurtherLinks` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`FurtherLinks` (
  `idFurtherLinks` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(1024) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idFurtherLinks`),
  INDEX `fk_Further_links_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`GlobalHospitalIdentifier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`GlobalHospitalIdentifier` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`GlobalHospitalIdentifier` (
  `idGlobalHospitalIdentifier` INT NOT NULL AUTO_INCREMENT,
  `ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idGlobalHospitalIdentifier`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Hospital` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Hospital` (
  `idHospital` INT NOT NULL AUTO_INCREMENT,
  `xmlFileName` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `alias` VARCHAR(1024) NULL DEFAULT NULL,
  `ikNumber` VARCHAR(255) NULL DEFAULT NULL,
  `locationNumberHospital` VARCHAR(255) NULL DEFAULT NULL,
  `locationNumberSite` VARCHAR(255) NULL DEFAULT NULL,
  `phoneHospital` VARCHAR(255) NULL DEFAULT NULL,
  `phoneLocation` VARCHAR(255) NULL DEFAULT NULL,
  `urlHospital` VARCHAR(1024) NULL DEFAULT NULL,
  `urlAdditionalInformation` VARCHAR(1024) NULL DEFAULT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  `HospitalOperator_idHospitalOperator` INT NOT NULL,
  `GlobalHospitalIdentifier_idGlobalHospitalIdentifier` INT NOT NULL,
  PRIMARY KEY (`idHospital`),
  INDEX `fk_Hospital_Hospitaloperator_idx` (`HospitalOperator_idHospitalOperator` ASC) VISIBLE,
  INDEX `fk_Hospital_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE,
  INDEX `fk_Hospital_GlobalHospitalIdentifier1_idx` (`GlobalHospitalIdentifier_idGlobalHospitalIdentifier` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`HospitalDataYear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`HospitalDataYear` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`HospitalDataYear` (
  `idHospitalDataYear` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idHospitalDataYear`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`HospitalKPI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`HospitalKPI` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`HospitalKPI` (
  `idHospitalKPI` INT NOT NULL AUTO_INCREMENT,
  `quantityBeds` VARCHAR(255) NULL,
  `quantityCasesFull` VARCHAR(255) NULL,
  `quantityCasesPartial` VARCHAR(255) NULL,
  `quantityCasesOutpatient` VARCHAR(255) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idHospitalKPI`),
  INDEX `fk_Hospitalkpi_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM
COMMENT = '	';


-- -----------------------------------------------------
-- Table `gbadata`.`HospitalOperator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`HospitalOperator` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`HospitalOperator` (
  `idHospitalOperator` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(2048) NOT NULL,
  `type` VARCHAR(1024) NULL,
  `alias` VARCHAR(2048) NULL,
  PRIMARY KEY (`idHospitalOperator`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`HygieneCommission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`HygieneCommission` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`HygieneCommission` (
  `idHygieneCommission` INT NOT NULL AUTO_INCREMENT,
  `HCisImplemented` VARCHAR(255) NOT NULL,
  `frequency` VARCHAR(255) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idHygieneCommission`),
  INDEX `fk_HygieneCommission_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`HygieneFurtherMeasures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`HygieneFurtherMeasures` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`HygieneFurtherMeasures` (
  `idHygieneFurtherMeasures` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `measure` VARCHAR(1024) NULL DEFAULT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idHygieneFurtherMeasures`),
  INDEX `fk_HygieneFurtherMeasures_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`HygieneMeasures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`HygieneMeasures` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`HygieneMeasures` (
  `idHygieneMeasures` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idHygieneMeasures`),
  INDEX `fk_HygieneMeasures_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`HygieneStaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`HygieneStaff` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`HygieneStaff` (
  `idHygieneStaff` INT NOT NULL AUTO_INCREMENT,
  `occupationalGroup` VARCHAR(255) NULL DEFAULT NULL,
  `amount` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idHygieneStaff`),
  INDEX `fk_HygieneStaff_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`InstrumentsInternalComSystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`InstrumentsInternalComSystem` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`InstrumentsInternalComSystem` (
  `idInstrumentsInternalComSystem` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `frequency` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idInstrumentsInternalComSystem`),
  INDEX `fk_InstrumentsInternalComSystem_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`InstrumentsRM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`InstrumentsRM` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`InstrumentsRM` (
  `idInstrumentsRM` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `SOP` VARCHAR(1024) NULL DEFAULT NULL,
  `date` DATE NULL,
  `caseConferences` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idInstrumentsRM`),
  INDEX `fk_InstrumentsRM_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`InternalComSystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`InternalComSystem` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`InternalComSystem` (
  `idInternalComSystem` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `frequency` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idInternalComSystem`),
  INDEX `fk_InternalComSystem_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`MeasuresQM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`MeasuresQM` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`MeasuresQM` (
  `idMeasuresQM` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idMeasuresQM`),
  INDEX `fk_MeasuresQM_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`MedicalDevices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`MedicalDevices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`MedicalDevices` (
  `idMedicalDevices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `24hEmergencyPresence` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idMedicalDevices`),
  INDEX `fk_MedicalDevices_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`MedicalExpertise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`MedicalExpertise` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`MedicalExpertise` (
  `idMedicalExpertise` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idMedicalExpertise`),
  INDEX `fk_MedicalExpertise_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`MedicalServices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`MedicalServices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`MedicalServices` (
  `idMedicalServices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idMedicalServices`),
  INDEX `fk_MedicalServices_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`MinimumQuantities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`MinimumQuantities` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`MinimumQuantities` (
  `idMinimumQuantities` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `quantity` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `dateSinceWhen` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idMinimumQuantities`),
  INDEX `fk_MinimumQuantities_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`MinimumQuantitiesPrognosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`MinimumQuantitiesPrognosis` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`MinimumQuantitiesPrognosis` (
  `idMinimumQuantitiesPrognosis` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `resultPrognosis` VARCHAR(255) NULL DEFAULT NULL,
  `prognosisReportingYear` VARCHAR(255) NULL DEFAULT NULL,
  `quantityQ34Q12` VARCHAR(255) NULL DEFAULT NULL,
  `auditByRegionalAuthority` VARCHAR(255) NULL DEFAULT NULL,
  `exceptionalCase` VARCHAR(255) NULL DEFAULT NULL,
  `resultOfAudit` VARCHAR(255) NULL DEFAULT NULL,
  `transitionalArrangement` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idMinimumQuantitiesPrognosis`),
  INDEX `fk_MinimumQuantitiesPrognosis_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`NonMedicalServices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`NonMedicalServices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`NonMedicalServices` (
  `idNonMedicalServices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `additionalInformation` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idNonMedicalServices`),
  INDEX `fk_NonMedicalServices_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`NursingExpertise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`NursingExpertise` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`NursingExpertise` (
  `idNursingExpertise` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idNursingExpertise`),
  INDEX `fk_NursingExpertise_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`NursingServices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`NursingServices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`NursingServices` (
  `idNursingServices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idNursingServices`),
  INDEX `fk_NursingServices_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`OutpatientOperations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`OutpatientOperations` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`OutpatientOperations` (
  `idOutpatientOperations` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL,
  `amount` VARCHAR(255) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idOutpatientOperations`),
  INDEX `fk_OutpatientOperations_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`OutpatientTreatments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`OutpatientTreatments` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`OutpatientTreatments` (
  `idOutpatientTreatments` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `codeMedicalServices` VARCHAR(255) NULL DEFAULT NULL,
  `nameOfotherCodes` VARCHAR(1024) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idOutpatientTreatments`),
  INDEX `fk_OutpatientTreatments_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Paragraph116b`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Paragraph116b` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Paragraph116b` (
  `idParagraph116b` INT NOT NULL AUTO_INCREMENT,
  `codeOutpatientTreatments` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `codeParagraph116b` VARCHAR(255) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idParagraph116b`),
  INDEX `fk_Paragraph116b_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Person` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `responsibility` VARCHAR(1024) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `fax` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Personnel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Personnel` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Personnel` (
  `idPersonnel` INT NOT NULL AUTO_INCREMENT,
  `occupationalGroup` VARCHAR(255) NULL DEFAULT NULL,
  `fulltimeStaff` VARCHAR(255) NULL DEFAULT NULL,
  `staffWithDirectEmployment` VARCHAR(255) NULL DEFAULT NULL,
  `staffWithoutDirectEmployment` VARCHAR(255) NULL DEFAULT NULL,
  `staffOutpatientCare` VARCHAR(255) NULL DEFAULT NULL,
  `staffInpatientCare` VARCHAR(255) NULL DEFAULT NULL,
  `casesPerStaffInpatientCare` VARCHAR(255) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idPersonnel`),
  INDEX `fk_Personnel_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`PersonnelHospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`PersonnelHospital` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`PersonnelHospital` (
  `idPersonnelHospital` INT NOT NULL AUTO_INCREMENT,
  `occupationalGroup` VARCHAR(255) NULL DEFAULT NULL,
  `fulltimeStaff` VARCHAR(255) NULL DEFAULT NULL,
  `staffWithDirectEmployment` VARCHAR(255) NULL DEFAULT NULL,
  `staffWithoutDirectEmployment` VARCHAR(255) NULL DEFAULT NULL,
  `staffOutpatientCare` VARCHAR(255) NULL DEFAULT NULL,
  `staffInpatientCare` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idPersonnelHospital`),
  INDEX `fk_PersonnelHospital_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`PharmaceuticalStaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`PharmaceuticalStaff` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`PharmaceuticalStaff` (
  `idPharmaceuticalStaff` INT NOT NULL AUTO_INCREMENT,
  `pharmacists` INT NOT NULL,
  `additionalStaff` INT NOT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idPharmaceuticalStaff`),
  INDEX `fk_pharmaceuticalStaff_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`PharmacotherapySafetyMeasures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`PharmacotherapySafetyMeasures` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`PharmacotherapySafetyMeasures` (
  `idPharmacotherapySafetyMeasures` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `furtherInformation` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idPharmacotherapySafetyMeasures`),
  INDEX `fk_PharmacotherapySafetyMeasures_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`PharmacotherapySteeringBoard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`PharmacotherapySteeringBoard` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`PharmacotherapySteeringBoard` (
  `idPharmacotherapySteeringBoard` INT NOT NULL AUTO_INCREMENT,
  `frequency` VARCHAR(255) NULL DEFAULT NULL,
  `involvedDepartments` VARCHAR(1024) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idPharmacotherapySteeringBoard`),
  INDEX `fk_PharmacotherapySteeringBoard_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Procedures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Procedures` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Procedures` (
  `idProcedures` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `amount` VARCHAR(255) NULL DEFAULT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idProcedures`),
  INDEX `fk_Procedures_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Qualitymanagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Qualitymanagement` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Qualitymanagement` (
  `idQualitymanagement` INT NOT NULL AUTO_INCREMENT,
  `frequency` VARCHAR(255) NULL,
  `involvedDepartments` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idQualitymanagement`),
  INDEX `fk_Qualitymanagement_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Relations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Relations` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Relations` (
  `idRelations` INT NOT NULL AUTO_INCREMENT,
  `Hospital_idHospital` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  `Person_idPerson` INT NOT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idRelations`),
  INDEX `fk_Relations_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  INDEX `fk_Relations_Person1_idx` (`Person_idPerson` ASC) VISIBLE,
  INDEX `fk_Relations_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE,
  INDEX `fk_Relations_Departments1_idx` (`Departments_idDepartments` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`Riskmanagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`Riskmanagement` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`Riskmanagement` (
  `idRiskmanagement` INT NOT NULL AUTO_INCREMENT,
  `frequency` VARCHAR(255) NULL,
  `involvedDepartments` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idRiskmanagement`),
  INDEX `fk_Riskmanagement_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`SpecialPersonnelHospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`SpecialPersonnelHospital` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`SpecialPersonnelHospital` (
  `idSpecialPersonnelHospital` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `fulltimeStaff` VARCHAR(255) NULL DEFAULT NULL,
  `staffWithDirectEmployment` VARCHAR(255) NULL DEFAULT NULL,
  `staffWithoutDirectEmployment` VARCHAR(255) NULL DEFAULT NULL,
  `staffOutpatientCare` VARCHAR(255) NULL DEFAULT NULL,
  `staffInpatientCare` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idSpecialPersonnelHospital`),
  INDEX `fk_PersonnelHospital_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`TrainingOtherHealthProfessionals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`TrainingOtherHealthProfessionals` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`TrainingOtherHealthProfessionals` (
  `idTrainingOtherHealthProfessionals` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(1024) NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idTrainingOtherHealthProfessionals`),
  INDEX `fk_Trainingotherhealthprofessionals_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`emergencyCare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`emergencyCare` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`emergencyCare` (
  `idemergencyCare` INT NOT NULL AUTO_INCREMENT,
  `noEmergencyCareLevel` INT NOT NULL,
  `emergencyCareLevelOne` INT NULL DEFAULT NULL,
  `emergencyCareLevelTwo` INT NULL DEFAULT NULL,
  `emergencyCareLevelThree` INT NULL DEFAULT NULL,
  `specializedCare` VARCHAR(512) NULL DEFAULT NULL,
  `cooperationKV` INT NULL DEFAULT NULL,
  `emergencyMedicalOffice` VARCHAR(255) NULL DEFAULT NULL,
  `emergencyServices` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idemergencyCare`),
  INDEX `fk_emergencyCare_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`emergencyCareSpecialModules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`emergencyCareSpecialModules` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`emergencyCareSpecialModules` (
  `idemergencyCareSpecialModules` INT NOT NULL AUTO_INCREMENT,
  `emergencyCareLevel` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `Hospital_idHospital` INT NOT NULL,
  PRIMARY KEY (`idemergencyCareSpecialModules`),
  INDEX `fk_emergencyCareSpecialModules_Hospital1_idx` (`Hospital_idHospital` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_academicteaching`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_academicteaching` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_academicteaching` (
  `idqb_list_academicteaching` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_academicteaching`),
  INDEX `fk_qb_list_academicteaching_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_accessibility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_accessibility` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_accessibility` (
  `idqb_list_accessibility` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(1024) NULL DEFAULT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_accessibility`),
  INDEX `fk_qb_list_accessibility_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_clinicalriskmanagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_clinicalriskmanagement` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_clinicalriskmanagement` (
  `idqb_list_clinicalriskmanagement` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_clinicalriskmanagement`),
  INDEX `fk_qb_list_clinicalriskmanagement_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_drugtherapysafety`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_drugtherapysafety` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_drugtherapysafety` (
  `idqb_list_drugtherapysafety` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `additionalInformation` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_drugtherapysafety`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_externalcomsystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_externalcomsystem` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_externalcomsystem` (
  `idqb_list_externalcomsystem` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_externalcomsystem`),
  INDEX `fk_qb_list_externalcomsystem_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_externalqualitymanagementbystate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_externalqualitymanagementbystate` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_externalqualitymanagementbystate` (
  `idqb_list_externalqualitymanagementbystate` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_externalqualitymanagementbystate`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_hygieneriskmanagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_hygieneriskmanagement` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_hygieneriskmanagement` (
  `idqb_list_hygieneriskmanagement` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_hygieneriskmanagement`),
  INDEX `fk_qb_list_hygieneriskmanagement_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_internalcomsystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_internalcomsystem` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_internalcomsystem` (
  `idqb_list_internalcomsystem` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_internalcomsystem`),
  INDEX `fk_qb_list_internalcomsystem_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_measuresqualitymanagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_measuresqualitymanagement` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_measuresqualitymanagement` (
  `idqb_list_measuresqualitymanagement` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_measuresqualitymanagement`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_medicaldevices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_medicaldevices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_medicaldevices` (
  `idqb_list_medicaldevices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `device` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `24hEmergencyPresence` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_medicaldevices`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_medicalexpertise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_medicalexpertise` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_medicalexpertise` (
  `idqb_list_medicalexpertise` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_medicalexpertise`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_medicalservices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_medicalservices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_medicalservices` (
  `idqb_list_medicalservices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_medicalservices`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_minimumquantitiesregulation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_minimumquantitiesregulation` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_minimumquantitiesregulation` (
  `idqb_list_minimumquantitiesregulation` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_minimumquantitiesregulation`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_nonmedicalservices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_nonmedicalservices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_nonmedicalservices` (
  `idqb_list_nonmedicalservices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `additionalInformation` VARCHAR(255) NULL DEFAULT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_nonmedicalservices`),
  INDEX `fk_qb_list_nonmedicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_nursingexpertise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_nursingexpertise` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_nursingexpertise` (
  `idqb_list_nursingexpertise` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_nursingexpertise`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_nursingservices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_nursingservices` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_nursingservices` (
  `idqb_list_nursingservices` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_nursingservices`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_outpatienttreatments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_outpatienttreatments` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_outpatienttreatments` (
  `idqb_list_outpatienttreatments` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_outpatienttreatments`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_paragraph116b`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_paragraph116b` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_paragraph116b` (
  `idqb_list_paragraph116b` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `codeOfAnnex` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_paragraph116b`),
  INDEX `fk_qb_list_medicalservices_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_specialemergencytreatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_specialemergencytreatment` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_specialemergencytreatment` (
  `idqb_list_specialemergencytreatment` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_specialemergencytreatment`),
  INDEX `fk_qb_list_specialemergencytreatment_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_therapeuticstaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_therapeuticstaff` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_therapeuticstaff` (
  `idqb_list_therapeuticstaff` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_therapeuticstaff`),
  INDEX `fk_qb_list_therapeuticstaff_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `gbadata`.`qb_list_trainingotherhealthprofessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gbadata`.`qb_list_trainingotherhealthprofessions` ;

CREATE TABLE IF NOT EXISTS `gbadata`.`qb_list_trainingotherhealthprofessions` (
  `idqb_list_trainingotherhealthprofessions` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `HospitalDataYear_idHospitalDataYear` INT NOT NULL,
  PRIMARY KEY (`idqb_list_trainingotherhealthprofessions`),
  INDEX `fk_qb_list_trainingotherhealthprofessions_HospitalDataYear1_idx` (`HospitalDataYear_idHospitalDataYear` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
